USE master
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = 'Grupo4')
    DROP DATABASE Grupo4
GO

CREATE DATABASE Grupo4
GO

USE Grupo4
GO

-- =====================
-- TABLAS
-- =====================

CREATE TABLE CURSOS(
	CICLO SMALLINT NOT NULL,
	ALIAS NVARCHAR(10) NOT NULL,
	NOMBRECURSO NVARCHAR(50)	
)
GO
ALTER TABLE CURSOS
ADD CONSTRAINT PK_CURSOS PRIMARY KEY (CICLO, ALIAS)
GO

CREATE TABLE MODULOS(
	CODIGOMODULO SMALLINT NOT NULL,
	CICLO SMALLINT NOT NULL,
	ALIAS NVARCHAR(10) NOT NULL,
	NOMBREM NVARCHAR(50) NOT NULL
)
GO
ALTER TABLE MODULOS
ADD CONSTRAINT [FK_MODULOS_CURSOS] FOREIGN KEY (CICLO, ALIAS) REFERENCES CURSOS(CICLO, ALIAS)
ALTER TABLE MODULOS
ADD CONSTRAINT [PK_MODULOS] PRIMARY KEY (CODIGOMODULO, CICLO, ALIAS)
GO

CREATE TABLE RAS(
	RA SMALLINT NOT NULL,
	CODIGOMODULO SMALLINT NOT NULL,
	CICLO SMALLINT NOT NULL,
	ALIAS NVARCHAR(10) NOT NULL,
	DESCRIPCION NVARCHAR(250) NOT NULL
)
GO
ALTER TABLE RAS
ADD CONSTRAINT [FK_RAS_MODULOS] FOREIGN KEY (CODIGOMODULO, CICLO, ALIAS) REFERENCES MODULOS(CODIGOMODULO, CICLO, ALIAS)
ALTER TABLE RAS
ADD CONSTRAINT PK_RAS PRIMARY KEY (RA, CODIGOMODULO, CICLO, ALIAS)
GO

CREATE TABLE ALUMNOS(
	DNI CHAR(9) PRIMARY KEY,
	HORASTOTALES SMALLINT NOT NULL,
	NOMBRE NVARCHAR(50) NOT NULL,
	[APELLIDO 1] NVARCHAR(50) NOT NULL,
	[APELLIDO 2] NVARCHAR(50) NOT NULL,
	CICLO SMALLINT NOT NULL,
	ALIAS NVARCHAR(10) NOT NULL
)
GO
ALTER TABLE ALUMNOS
ADD CONSTRAINT FK_ALUMNOS_CURSOS FOREIGN KEY (CICLO, ALIAS) REFERENCES CURSOS(CICLO, ALIAS)
GO

CREATE TABLE JORNADAS(
	FECHA DATETIME NOT NULL,
	DNI CHAR(9) NOT NULL,
	DURACION DECIMAL(2,0) NOT NULL
)
GO
ALTER TABLE JORNADAS
ADD CONSTRAINT FK_JORNADAS_ALUMNOS FOREIGN KEY (DNI) REFERENCES ALUMNOS(DNI)
ALTER TABLE JORNADAS
ADD CONSTRAINT PK_JORNADAS PRIMARY KEY (FECHA, DNI)
GO

CREATE TABLE TAREASREALIZADAS(
	CODIGOTAREA SMALLINT NOT NULL,
	FECHAJORNADA DATETIME NOT NULL,
	DNI CHAR(9) NOT NULL,
	DESCRIPCION NVARCHAR(250) NOT NULL,
	DURACION DECIMAL(2,0) NOT NULL
)
GO
ALTER TABLE TAREASREALIZADAS
ADD CONSTRAINT FK_TAREASREALIZADAS_JORNADAS FOREIGN KEY (FECHAJORNADA, DNI) REFERENCES JORNADAS(FECHA,DNI)
ALTER TABLE TAREASREALIZADAS
ADD CONSTRAINT PK_TAREASREALIZADAS PRIMARY KEY (CODIGOTAREA, FECHAJORNADA, DNI)
GO

CREATE TABLE INCLUYEN(
	CODIGOTAREA SMALLINT NOT NULL,
	FECHAJORNADA DATETIME NOT NULL,
	DNI CHAR(9) NOT NULL,
	RA SMALLINT NOT NULL,
	CODIGOMODULO SMALLINT NOT NULL,
	CICLO SMALLINT NOT NULL,
	ALIAS NVARCHAR(10) NOT NULL
)
GO
ALTER TABLE INCLUYEN
ADD CONSTRAINT FK_INCLUYEN_TAREASREALIZADAS FOREIGN KEY (CODIGOTAREA, FECHAJORNADA, DNI) REFERENCES TAREASREALIZADAS(CODIGOTAREA, FECHAJORNADA,DNI)
ALTER TABLE INCLUYEN
ADD CONSTRAINT FK_INCLUYEN_RAS FOREIGN KEY (RA, CODIGOMODULO, CICLO, ALIAS) REFERENCES RAS(RA, CODIGOMODULO, CICLO, ALIAS)
ALTER TABLE INCLUYEN
ADD CONSTRAINT PK_INCLUYEN PRIMARY KEY (CODIGOTAREA, FECHAJORNADA, DNI, RA, CODIGOMODULO, CICLO, ALIAS)
GO

-- =====================
-- RULES
-- =====================

CREATE RULE CICLOS AS (@CAMPO = 1 OR @CAMPO = 2)
GO
EXEC SP_BINDRULE CICLOS, 'CURSOS.CICLO'
EXEC SP_BINDRULE CICLOS, 'MODULOS.CICLO'
EXEC SP_BINDRULE CICLOS, 'RAS.CICLO'
EXEC SP_BINDRULE CICLOS, 'ALUMNOS.CICLO'
EXEC SP_BINDRULE CICLOS, 'INCLUYEN.CICLO'
GO

CREATE RULE DNIS AS (@CAMPO LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]')
GO
EXEC SP_BINDRULE DNIS, 'ALUMNOS.DNI'
EXEC SP_BINDRULE DNIS, 'JORNADAS.DNI'
EXEC SP_BINDRULE DNIS, 'TAREASREALIZADAS.DNI'
EXEC SP_BINDRULE DNIS, 'INCLUYEN.DNI'
GO

CREATE RULE MAYORFECHAACTUAL AS (@CAMPO <= GETDATE())
GO
EXEC SP_BINDRULE MAYORFECHAACTUAL, 'JORNADAS.FECHA'
EXEC SP_BINDRULE MAYORFECHAACTUAL, 'TAREASREALIZADAS.FECHAJORNADA'
EXEC SP_BINDRULE MAYORFECHAACTUAL, 'INCLUYEN.FECHAJORNADA'
GO

CREATE RULE MAXIMADURACION AS (@CAMPO BETWEEN 0 AND 8)
GO
EXEC SP_BINDRULE MAXIMADURACION, 'JORNADAS.DURACION'
EXEC SP_BINDRULE MAXIMADURACION, 'TAREASREALIZADAS.DURACION'
GO

-- =====================
-- DEFAULTS
-- =====================

CREATE DEFAULT HOY AS (GETDATE())
GO
EXEC SP_BINDEFAULT HOY, 'JORNADAS.FECHA'
EXEC SP_BINDEFAULT HOY, 'TAREASREALIZADAS.FECHAJORNADA'
EXEC SP_BINDEFAULT HOY, 'INCLUYEN.FECHAJORNADA'
GO

-- =====================
-- STORED PROCEDURES
-- =====================
GO
CREATE PROCEDURE AUTOINDEXADO_MODULOS
	@CICLO SMALLINT,
	@ALIAS NVARCHAR(10),
	@NOMBREMODULO NVARCHAR(50)
AS
    IF NOT EXISTS (SELECT CODIGOMODULO FROM MODULOS
                    WHERE CICLO = @CICLO AND ALIAS = @ALIAS AND NOMBREM = @NOMBREMODULO)
	    BEGIN
            INSERT INTO MODULOS (CODIGOMODULO, CICLO, ALIAS, NOMBREM)
            VALUES (
                (SELECT ISNULL(MAX(CODIGOMODULO), 0) 
                FROM MODULOS 
                WHERE CICLO = @CICLO AND ALIAS = @ALIAS) + 1, 
                @CICLO, 
                @ALIAS,
                @NOMBREMODULO)
        END

GO
CREATE PROCEDURE AUTOINDEXADO_RAS
    @CICLO SMALLINT,
	@ALIAS NVARCHAR(10),
	@CODIGOMODULO SMALLINT,
    @DESCRIPCION NVARCHAR(250)
AS
    IF NOT EXISTS (SELECT RA FROM RAS
                    WHERE CICLO = @CICLO AND ALIAS = @ALIAS AND CODIGOMODULO = @CODIGOMODULO AND DESCRIPCION = @DESCRIPCION)
	    BEGIN
            INSERT INTO RAS (RA, CODIGOMODULO, CICLO, ALIAS, DESCRIPCION)
            VALUES (
                (SELECT ISNULL(MAX(RA), 0) 
                FROM RAS 
                WHERE CICLO = @CICLO AND ALIAS = @ALIAS AND CODIGOMODULO = @CODIGOMODULO) + 1, 
                @CODIGOMODULO,
                @CICLO, 
                @ALIAS,
                @DESCRIPCION)
        END
	
GO
CREATE PROCEDURE AUTOINDEXADO_TAREASREALIZADAS
    @FECHAJORNADA DATETIME,
	@DNI CHAR(9),
    @DESCRIPCION NVARCHAR(250),
    @DURACION DECIMAL(2, 0)
AS
    IF NOT EXISTS (SELECT CODIGOTAREA FROM TAREASREALIZADAS
                    WHERE FECHAJORNADA = @FECHAJORNADA AND DNI = @DNI AND DESCRIPCION = @DESCRIPCION)
	    BEGIN
            INSERT INTO TAREASREALIZADAS(CODIGOTAREA, FECHAJORNADA, DNI, DESCRIPCION, DURACION)
            VALUES (
                (SELECT ISNULL(MAX(CODIGOTAREA), 0) 
                FROM TAREASREALIZADAS
                WHERE FECHAJORNADA = @FECHAJORNADA AND DNI = @DNI) + 1, 
                @FECHAJORNADA,
                @DNI,
                @DESCRIPCION,
                @DURACION)
        END

GO
CREATE PROCEDURE HorasTrabajadasDeAlumno
	@Nombre NVARCHAR(50), 
	@Apellido1 NVARCHAR(50), 
	@Apellido2 NVARCHAR(50)
AS
	RETURN(SELECT SUM(JORNADAS.DURACION)
		FROM JORNADAS INNER JOIN ALUMNOS ON JORNADAS.DNI = ALUMNOS.DNI
		WHERE NOMBRE = @Nombre AND [APELLIDO 1] = @Apellido1 AND [APELLIDO 2] = @Apellido2)
