CREATE DATABASE Grupo4
--DROP DATABASE Grupo4

USE Grupo4

CREATE TABLE CURSOS(
	CICLO SMALLINT NOT NULL,
	ALIAS NVARCHAR(10) NOT NULL,
	NOMBRECURSO NVARCHAR(50)	
)
--PK Cursos
ALTER TABLE CURSOS
ADD CONSTRAINT PK_CURSOS PRIMARY KEY (CICLO, ALIAS)

--Crear tabla MODULOS
CREATE TABLE MODULOS(
	CODIGOMODULO SMALLINT NOT NULL,
	CICLO SMALLINT NOT NULL,
	ALIAS NVARCHAR(10) NOT NULL,
	NOMBREM NVARCHAR(50) NOT NULL
)
--FK Modulos
ALTER TABLE MODULOS
ADD CONSTRAINT [FK_MODULOS_CURSOS] FOREIGN KEY (CICLO, ALIAS) REFERENCES CURSOS(CICLO, ALIAS)
--PK MODULOS
ALTER TABLE MODULOS
ADD CONSTRAINT [PK_MODULOS] PRIMARY KEY (CODIGOMODULO, CICLO, ALIAS)

--Crear tabla RAS
CREATE TABLE RAS(
	RA SMALLINT NOT NULL,
	CODIGOMODULO SMALLINT NOT NULL,
	CICLO SMALLINT NOT NULL,
	ALIAS NVARCHAR(10) NOT NULL,
	DESCRIPCION NVARCHAR(250) NOT NULL
)
--FK RAS
ALTER TABLE RAS
ADD CONSTRAINT [FK_RAS_MODULOS] FOREIGN KEY (CODIGOMODULO, CICLO, ALIAS) REFERENCES MODULOS(CODIGOMODULO, CICLO, ALIAS)
--PK RAS
ALTER TABLE RAS
ADD CONSTRAINT PK_RAS PRIMARY KEY (RA, CODIGOMODULO, CICLO, ALIAS)

--Crear tabla ALUMNOS
CREATE TABLE ALUMNOS(
	DNI CHAR(9) PRIMARY KEY,
	HORASTOTALES SMALLINT NOT NULL,
	NOMBRE NVARCHAR(50) NOT NULL,
	[APELLIDO 1] NVARCHAR(50) NOT NULL,
	[APELLIDO 2] NVARCHAR(50) NOT NULL,
	CICLO SMALLINT NOT NULL,
	ALIAS NVARCHAR(10) NOT NULL
)
--FK Alumnos
ALTER TABLE ALUMNOS
ADD CONSTRAINT FK_ALUMNOS_CURSOS FOREIGN KEY (CICLO, ALIAS) REFERENCES CURSOS(CICLO, ALIAS)

--Crear tabla JORNADAS
CREATE TABLE JORNADAS(
	FECHA DATETIME NOT NULL,
	DNI CHAR(9) NOT NULL,
	DURACION SMALLINT NOT NULL
)
--FK Jornadas
ALTER TABLE JORNADAS
ADD CONSTRAINT FK_JORNADAS_ALUMNOS FOREIGN KEY (DNI) REFERENCES ALUMNOS(DNI)
--PK Jornadas
ALTER TABLE JORNADAS
ADD CONSTRAINT PK_JORNADAS PRIMARY KEY (FECHA, DNI)

--Crear tabla TAREASREALIZADAS
CREATE TABLE TAREASREALIZADAS(
	CODIGOTAREA SMALLINT NOT NULL,
	FECHAJORNADA DATETIME NOT NULL,
	DNI CHAR(9) NOT NULL,
	DESCRIPCION NVARCHAR(50) NOT NULL,
	DURACION SMALLINT NOT NULL
)
--FK TareasRealizadas
ALTER TABLE TAREASREALIZADAS
ADD CONSTRAINT FK_TAREASREALIZADAS_JORNADAS FOREIGN KEY (FECHAJORNADA, DNI) REFERENCES JORNADAS(FECHA,DNI)
--PK TareasRealizadas
ALTER TABLE TAREASREALIZADAS
ADD CONSTRAINT PK_TAREASREALIZADAS PRIMARY KEY (CODIGOTAREA, FECHAJORNADA, DNI)

--Crear tabla INCLUYEN
CREATE TABLE INCLUYEN(
	CODIGOTAREA SMALLINT NOT NULL,
	FECHAJORNADA DATETIME NOT NULL,
	DNI CHAR(9) NOT NULL,
	RA SMALLINT NOT NULL,
	CODIGOMODULO SMALLINT NOT NULL,
	CICLO SMALLINT NOT NULL,
	ALIAS NVARCHAR(10) NOT NULL
)
--FK TareasRealizadas
ALTER TABLE INCLUYEN
ADD CONSTRAINT FK_INCLUYEN_TAREASREALIZADAS FOREIGN KEY (CODIGOTAREA, FECHAJORNADA, DNI) REFERENCES TAREASREALIZADAS(CODIGOTAREA, FECHAJORNADA,DNI)
ALTER TABLE INCLUYEN
ADD CONSTRAINT FK_INCLUYEN_RAS FOREIGN KEY (RA, CODIGOMODULO, CICLO, ALIAS) REFERENCES RAS(RA, CODIGOMODULO, CICLO, ALIAS)
--PK Incluyen
ALTER TABLE INCLUYEN
ADD CONSTRAINT PK_INCLUYEN PRIMARY KEY (CODIGOTAREA, FECHAJORNADA, DNI, RA, CODIGOMODULO, CICLO, ALIAS)


CREATE RULE CICLOS AS (@CAMPO = 1 OR @CAMPO = 2)

SP_BINDRULE CICLOS , 'CURSOS.CICLO'
EXEC SP_BINDRULE CICLOS , 'MODULOS.CICLO'
EXEC SP_BINDRULE CICLOS , 'RAS.CICLO'
EXEC SP_BINDRULE CICLOS , 'ALUMNOS.CICLO'
EXEC SP_BINDRULE CICLOS , 'INCLUYEN.CICLO'


CREATE RULE DNIS AS (@CAMPO LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]')

SP_BINDRULE DNIS, 'ALUMNOS.DNI'
EXEC SP_BINDRULE DNIS, 'JORNADAS.DNI'
EXEC SP_BINDRULE DNIS, 'TAREASREALIZADAS.DNI'
EXEC SP_BINDRULE DNIS, 'INCLUYEN.DNI'


CREATE RULE MAYORFECHAACTUAL  AS (@CAMPO<=GETDATE())

SP_BINDRULE MAYORFECHAACTUAL ,'JORNADAS.FECHA'
EXEC SP_BINDRULE MAYORFECHAACTUAL ,'TAREASREALIZADAS.FECHAJORNADA'
EXEC SP_BINDRULE MAYORFECHAACTUAL ,'INCLUYEN.FECHAJORNADA '


CREATE DEFAULT HOY AS (GETDATE())

SP_BINDEFAULT HOY, 'JORNADAS.FECHA'
EXEC SP_BINDEFAULT HOY, 'TAREASREALIZADAS.FECHAJORNADA'
EXEC SP_BINDEFAULT HOY, 'INCLUYEN.FECHAJORNADA'

CREATE RULE MAXIMADURACION AS (@CAMPO BETWEEN 0 AND 8 )

SP_BINDRULE MAXIMADURACION , 'JORNADAS.DURACION'
EXEC SP_BINDRULE MAXIMADURACION , 'TAREASREALIZADAS.DURACION'


CREATE PROCEDURE SP_InsertarModulo
    @CICLO SMALLINT, 
    @ALIAS NVARCHAR(10),
    @NOMBREM NVARCHAR(50) -- 1. Agregamos el parámetro que falta
AS
BEGIN
    INSERT INTO MODULOS (CODIGOMODULO, CICLO, ALIAS, NOMBREM) -- 2. Especificamos columnas
    VALUES (
        (SELECT ISNULL(MAX(CODIGOMODULO), 0) 
         FROM MODULOS 
         WHERE CICLO = @CICLO AND ALIAS = @ALIAS) + 1, 
        @CICLO, 
        @ALIAS,
        @NOMBREM -- 3. Enviamos el valor
    )
END



CREATE PROCEDURE SP_InsertarTareas
    @FECHAJORNADA DATETIME, 
    @DNI CHAR(9)
    -- Si faltan datos (ej. @DESCRIPCION), agrégalos aquí como parámetros
AS
BEGIN
    INSERT INTO TAREASREALIZADAS (CODIGOTAREA, FECHAJORNADA, DNI) -- Indica las columnas destino
    VALUES (
        (SELECT ISNULL(MAX(CODIGOTAREA), 0)
         FROM TAREASREALIZADAS
         WHERE FECHAJORNADA = @FECHAJORNADA AND DNI = @DNI) + 1, 
        @FECHAJORNADA, 
        @DNI
    )
END

